---
- name: Restart ifpromisc service
  systemd:
    daemon_reload: true
    state: restarted
    enabled: true
    name: ifpromisc.service

- name: Reboot ifpromisc
  reboot:
    msg: Rebooting because promiscuous mode was enabled
  when: service_install.changed