---
# Connection
ansible_host: 192.168.9.12
ansible_user: pi
ansible_connection: ssh
ansible_ssh_port: "{{ security_ssh_port }}"
ansible_ssh_private_key_file: /home/leonch/.ssh/pihole
ansible_ssh_public_key_file: "{{ lookup('file', '~/.ssh/pihole.pub') }}"
ansible_become_password: "{{ raspberrypi_sudo_password }}"
host_become_password: "{{ raspberrypi_sudo_password }}"

docker_install_compose: false

pi_network: "pi_network"

pihole_network: "{{ '.'.join(ipv4lan_network.split('.')[0:2]) }}.9.0/24"
pihole_network_base: "{{ '.'.join(pihole_network.split('.')[0:3]) }}"
pihole_network_gateway: "{{ '.'.join(pihole_network.split('.')[0:3]) }}.1"

# Packages to be installed for specific host
specific_packages:
  - netplan.io

enable_powersaving: no
# System specific variables
timezone: Europe/Amsterdam
guid: "1000"

# enable variables
enable_pidns: yes
enable_netplan_config: yes
enable_pihole: yes
enable_cloudflareddns: yes
ipv4static_dns: "1.1.1.1"
ipv6static_dns: "2606:4700:4700"