---
# Connection
ansible_host: 192.168.2.12
ansible_user: pi
ansible_connection: ssh
ansible_ssh_port: "{{ security_ssh_port }}"
ansible_ssh_private_key_file: /home/leonch/.ssh/pihole
ansible_ssh_public_key_file: "{{ lookup('file', '~/.ssh/pihole.pub') }}"
ansible_become_password: "{{ raspberrypi_sudo_password }}"
host_become_password: "{{ raspberrypi_sudo_password }}"

ssh_keys:
  - name: default user ssh key
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', '~/.ssh/pihole.pub') | default('') }}"


docker_install_compose: false

pihole_hostname: piholeunbound
pi_network: "pi_network"

# Packages to be installed for specific host
specific_packages:
  - netplan.io

enable_powersaving: no
# System specific variables
timezone: Europe/Amsterdam
guid: "1000"

# enable variables
enable_pihole: yes
enable_cloudflareddns: yes
ipv4static_dns: "1.1.1.1"
ipv6static_dns: "2606:4700:4700"
pihole_dns: "1.1.1.1;2606:4700:4700::1111"