---
# Connection
ansible_host: 192.168.2.12
ansible_user: pi
ansible_connection: ssh
ansible_ssh_port: "{{ security_ssh_port }}"
ansible_ssh_private_key_file: /home/leonch/.ssh/pihole
ansible_ssh_public_key_file: "{{ lookup('file', '~/.ssh/pihole.pub') }}"
ansible_become_password: "{{ raspberrypi_sudo_password }}"
host_become_password: "{{ raspberrypi_sudo_password }}"

# Apt mirrors
version: focal
apt_mirror: http://ports.ubuntu.com/ubuntu-ports

docker_install_compose: false

pi_network: "pi_internal"

pihole_network: "{{ '.'.join(lan_gateway.split('.')[0:2]) }}.8.0/24"
pihole_network_base: "{{ '.'.join(pihole_network.split('.')[0:3]) }}"
pihole_network_gateway: "{{ pihole_network_base }}.1"
pihole_network_mac: 2a:16:80:e1:1b:9c
# Packages to be installed for specific host
specific_packages:
  - netplan.io

enable_powersaving: no
# System specific variables
timezone: Europe/Amsterdam
guid: "1000"

# enable variables
enable_pidns: yes
enable_network_interface: no
enable_macvlan_interface: no
enable_pihole: yes
enable_cloudflareddns: yes
ipv4static_dns: "1.1.1.1"
ipv6static_dns: "2606:4700:4700"