---
collections:
  - name: geerlingguy.docker
  - name: viasite-ansible.zsh
  - name: ironicbadger.snapraid
  - name: geerlingguy.ntp
  - name: geerlingguy.pip
  - name: geerlingguy.security
  - name: geerlingguy.docker_arm
  - name: oefenweb.dns