---
roles:
  - name: geerlingguy.docker
  - name: quantumfate.zsh
  - name: ironicbadger.snapraid
  - name: geerlingguy.ntp
  - name: geerlingguy.pip
  - name: geerlingguy.security
  - name: geerlingguy.docker_arm
  - name: oefenweb.dns
  - name: notmycloud.ssh_port_fingerprint