---
- hosts: all
  become: yes
  gather_facts: no

  pre_tasks:
    - import_tasks: tasks/ssh_juggle_port.yml

  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/essential.yml
    - import_tasks: tasks/list_services.yml
    
  handlers:
    - name: Restart SSH daemon
      service:
        name: sshd
        state: restarted

- hosts: all
  become: yes
  gather_facts: yes


  tasks:
  - name: Gathering information about proccessor architecture
    import_tasks: tasks/repo_arch.yml

  - name: Icluding roles for simple tasks on machine without container
    import_tasks: tasks/include_role/simple_roles.yml
    when: enable_simple_roles | default(False)
  

  - name: Run geerlingguy pip role
    include_role:
      name: geerlingguy.pip
      apply:
        tags:
          - pip
          - python
          - docker
  
  - name: Run geerlingguy Docker arm role
    include_role:
      name: geerlingguy.docker_arm
      apply:
        tags:
          - docker
    when: inventory_hostname in groups['pi']

  - name: Run geerlingguy Docker arm role
    include_role:
      name: geerlingguy.docker
      apply:
        tags:
          - docker
    when: inventory_hostname in groups['main']

  - name: Icluding container roles for system
    import_tasks: tasks/include_role/system_container.yml
    when: enable_systemcontainer_roles | default(False)

  - name: Icluding container roles for web
    import_tasks: tasks/include_role/web_container.yml
    when: enable_webcontainer_roles | default(False)

  - name: Run the role for homer
    include_role:
      name: homer
      apply:
        tags:
        - homer
        - docker
    when: enable_container_homer | default(False)

  #   ### Run this at the end, when the environment is set
  #   - role: viasite-ansible.zsh
  #     tags:
  #       - zsh

  # # - role: ironicbadger.ansible_role_snapraid
  # #   become: yes
  # #   tags:
  # #     - snapraid
  # #   when: host_has_persistent_data | default(False)

  # #
  # # homer
  # #
  # - role: homer
  #   become: no
  #   tags:
  #     - homer
  #     - containers
  #   when: enable_container_homer | default(False)
