---
- hosts: all
  become: yes
  gather_facts: no

  pre_tasks:
    - import_tasks: tasks/ssh_juggle_port.yml

  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/essential.yml
    - import_tasks: tasks/list_services.yml
    - import_tasks: tasks/repo_arch.yml

  handlers:
    - name: Restart SSH daemon
      service:
        name: sshd
        state: restarted

- hosts: all
  become: yes
  gather_facts: yes

  
  tasks:
  - import_tasks: tasks/include_role/simple_roles.yml

  roles:
  # Setup docker and everything neccessary
  - role: geerlingguy.pip
    tags:
      - pip
      - python
      - docker

  - role: geerlingguy.docker_arm
    tags:
      - docker
    when: inventory_hostname in groups['pi']

  - role: geerlingguy.docker
    tags:
      - docker
    when: inventory_hostname in groups['main']

- hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - import_tasks: tasks/include_role/system_container.yml
  - import_tasks: tasks/include_role/web_container.yml
  
  roles:

    - role: homer
      tags:
        - homer
        - docker
      when: enable_container_homer | default(False)
  #   ### Run this at the end, when the environment is set
  #   - role: viasite-ansible.zsh
  #     tags:
  #       - zsh

  # # - role: ironicbadger.ansible_role_snapraid
  # #   become: yes
  # #   tags:
  # #     - snapraid
  # #   when: enable_nas_stuff | default(False)

  # #
  # # homer
  # #
  # - role: homer
  #   become: no
  #   tags:
  #     - homer
  #     - containers
  #   when: enable_container_homer | default(False)
