---
- name: Juggling the port and gather no facts is off
  hosts: all
  become: yes
  gather_facts: no

  pre_tasks:
  - name: Importing the task to juggle ports
    import_tasks: tasks/ssh_juggle_port.yml
    tags:
      - always
      - port
      - ssh
      
  - name: Run very essential tasks against server to ensure success of subsequent runs
    ansible.builtin.import_tasks: tasks/essential.yml
    tags:
      - always
  tags:
    - all

- name: Implementing basic Security and running system essential tasks
  hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
  - name: Requiring the list of services
    import_tasks: tasks/list_services.yml
    tags:
      - always

  - name: Gathering information about proccessor architecture
    import_tasks: tasks/repo_arch.yml
    tags:
      - always

  roles:
  - role: system/essential
    tags: 
      - system
    when: enable_essential | default(False)

  - role: geerlingguy.security
    tags:
      - security
    when: enable_security | default(False)

  tasks:
    - name: Reload the ssh service
      service:
        name: ssh
        state: restarted

  tags:
    - all

- name: Implement basic security and prepare the system for docker specific tasks
  hosts: all
  become: yes
  gather_facts: yes
  
  pre_tasks:
    - name: Making sure the correct port is set
      import_tasks: tasks/ensure_ssh_port.yml
      tags:
        - port
  
  roles:

  - role: security/iptables
    tags:
      - iptables
      - security
    when: (enable_iptables | default(False)) and (security_ssh_port == ansible_ssh_port | default(False))

  - role: oefenweb.dns
    tags:
      - dns
      - network
      - security
    when: enable_dns | default(False)
  
  - role: system/docker
    tags: 
      - docker
    when: enable_docker | default(False)

  tags:
    - all

- name: Prepare the picluster for network operations
  hosts: picluster
  become: yes
  gather_facts: yes

  roles:

  ## Network
  - role: network/pidns
    tags: 
      - pihole
      - containers
      - docker
      - network
    when: enable_pidns | default (False)

  - role: webservices/network/pihole
    tags: 
      - pihole
      - containers
      - docker
      - network
    when: enable_pihole | default(False)

  - role: network/cloudflareddns
    tags: 
      - cloudflareddns
      - containers
      - docker
      - network
    when: enable_cloudflareddns | default(False)

  tags:
    - picluster

- name: Run NAS specific tasks on the main machine
  hosts: main
  become: yes
  gather_facts: yes

  roles:

  ## Network
  - role: network/swag
    tags:
        - swag
        - network
        - docker
    when: enable_swag | default(False)

  ## Filesystem
  - role: filesystems/drives
    become: yes
    tags:
      - filesystems
      - drives
    when: enable_drives | default(False)

  - role: filesystems/mergerfs
    tags:
        - filesystems
        - mergerfs
    when: enable_mergerfs | default(False)

  - role: filesystems/mount
    become: yes
    tags:
        - filesystems
        - mount
    when: enable_mount | default(False)

  - role: homer
    tags:
        - homer
        - containers
    when: enable_homer | default(False)
  
  # # - role: ironicbadger.ansible_role_snapraid
  # #   become: yes
  # #   tags:
  # #     - filesystems
  # #     - snapraid
  # #   when: docker_persistent_data | default(False)

  tags:
    - main

- name: Make sure the environment is setup properly
  hosts: all
  become: yes
  gather_facts: yes

  roles:

  - role: quantumfate.zsh
    vars:
      zsh_user: "{{ ansible_user }}"
    tags:
      - zsh
      - dotfiles
