---
- hosts: all
  become: yes
  gather_facts: no

  pre_tasks:
    - import_tasks: tasks/ssh_juggle_port.yml
      tags:
        - port

- hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
  - name: Requiring the list of services
    import_tasks: tasks/list_services.yml

  - name: Gathering information about proccessor architecture
    import_tasks: tasks/repo_arch.yml

  roles:
  - role: system/essential
    tags: 
      - system
    when: enable_essential | default(False)

  - role: geerlingguy.security
    tags:
      - security
    when: enable_security | default(False)

  - role: oefenweb.dns
    tags:
      - dns
    when: enable_dns | default(False)

  - role: geerlingguy.pip
    tags:
      - pip
      - python
      - docker
    when: enable_docker | default(False)

- hosts: raspberrypi
  become: yes
  gather_facts: yes

  pre_tasks:
    - import_tasks: tasks/ensure_ssh_port.yml

  roles:

  - name: Run geerlingguy Docker arm role
    include_role:
      name: geerlingguy.docker_arm
      apply:
        tags:
          - docker

- hosts: quantumhome
  become: yes
  gather_facts: yes

  pre_tasks:
    - import_tasks: tasks/ensure_ssh_port.yml

  tasks:

  - name: Run geerlingguy Docker role
    include_role:
      name: geerlingguy.docker
      apply:
        tags:
          - docker


  - name: Run the role for homer
    include_role:
      name: homer
      apply:
        tags:
        - homer
        - docker
    when: enable_homer | default(False)

  #   ### Run this at the end, when the environment is set
  #   - role: viasite-ansible.zsh
  #     tags:
  #       - zsh

  # # - role: ironicbadger.ansible_role_snapraid
  # #   become: yes
  # #   tags:
  # #     - snapraid
  # #   when: host_has_persistent_data | default(False)

  # #
  # # homer
  # #
  # - role: homer
  #   become: no
  #   tags:
  #     - homer
  #     - containers
  #   when: enable_homer | default(False)
