---
- hosts: all
  become: yes

  pre_tasks:
    - import_tasks: tasks/juggle_port.yml
    - import_taksk: tasks/ssh.yml
    - import_tasks: tasks/essential.yml
    - import_tasks: tasks/list_services.yml
    - import_tasks: tasks/repo_arch.yml

  roles:
    # Install basics on all hosts (quality of life changes + docker)
    - role: system
      tags: 
        - system

    # Setup docker and everything neccessary 
    - role: geerlingguy.pip
      tags:
        - pip
        - python
        - docker

    - role: geerlingguy.docker_arm
      tags: 
        - docker
      when: inventory_hostname in groups['pi']

    - role: geerlingguy.docker
      tags: 
        - docker
      when: inventory_hostname in groups['main']
    
    - role: docker
      tags:
        - docker

#####################################################

- hosts: raspberrypi
  become: yes

  roles:
    - role: network/cloudflare-ddns
      become: no
      tags:
        - cloudflare-ddns
        - containers
      when: enable_cloudflare_ddns | default(False)
    
    - role: network/pihole
      become: no
      tags:
        - pihole
        - containers
      when: enable_raspberry_pihole | default(False)
        
- hosts: all
  become: yes

  roles:
    ### Run this at the end, when the environment is set
    - role: viasite-ansible.zsh
      tags:
        - system
        - zsh
    # Security
    #
    # - role: security
    #   tags: 
    #     - security
    #   when: enable_security | default(False)

    # - role: security/iptables
    #   tags:
    #     - security

    #
    # Network
    #

    # - role: network/swag
    #   become: no
    #   tags:
    #     - swag
    #     - containers
    #   when: enable_swag_public | default(False) or enable_swag_internal | default(False)

    # - role: network/bunkerized-nginx
    #   become: no
    #   tags:
    #     - bunkerized-nginx
    #     - containers
    #   when: enable_bunkerized_nginx | default(False)

    # #
    # # Filesystem
    # #

    # - role: filesystems/mergerfs
    #   tags: 
    #     - mergerfs
    #   when: enable_mergerfs | default(False)
    
    # - role: filesystems/mount
    #   tags: 
    #     - mount
    #   when: enable_mounting | default(False)
    
    # # - role: ironicbadger.ansible_role_snapraid
    # #   become: yes
    # #   tags:
    # #     - snapraid
    # #   when: enable_nas_stuff | default(False)

    # #
    # # homer
    # #
    # - role: homer
    #   become: no
    #   tags:
    #     - homer
    #     - containers
    #   when: enable_homer | default(False)

