---
- hosts: all
  become: yes

  pre_tasks:
    - import_tasks: tasks/essential.yml
    - tag: essential basis
  
- hosts: all
  become: yes
  
  roles:
    - role: system
      tags: 
        - system
    - role: security
      tags: 
        - security
