---
- hosts: all
  become: yes
  gather_facts: no

  pre_tasks:
    - import_tasks: tasks/ssh_juggle_port.yml
      tags:
        - port

  tags:
    - all

- hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
  - name: Requiring the list of services
    import_tasks: tasks/list_services.yml
    tags:
      - always

  - name: Gathering information about proccessor architecture
    import_tasks: tasks/repo_arch.yml
    tags:
      - always

  roles:
  - role: system/essential
    tags: 
      - system
    when: enable_essential | default(False)

  - role: geerlingguy.security
    tags:
      - security
    when: enable_security | default(False)

  tags:
    - all

- hosts: all
  become: yes
  gather_facts: yes
  
  pre_tasks:
  - import_tasks: tasks/ssh_juggle_port.yml
    tags:
      - port
  - import_tasks: tasks/ensure_ssh_port.yml
  
  roles:

  - role: security/iptables
    tags:
      - iptables
      - security
    when: (enable_iptables | default(False)) and (security_ssh_port == ansible_ssh_port | default(False))

  - role: oefenweb.dns
    tags:
      - dns
      - network
      - security
    when: enable_dns | default(False)
  
  - role: system/docker
    tags: 
      - docker
    when: enable_docker | default(False)

  tags:
    - all

- hosts: picluster
  become: yes
  gather_facts: yes

  roles:

  ## Network
  - role: webservices/network/pihole
    tags: 
      - pihole
      - containers
      - docker
    when: enable_pihole | default(False)

  - role: network/cloudflareddns
    tags: 
      - cloudflareddns
      - containers
      - docker
    when: enable_cloudflareddns | default(False)

  tags:
    - picluster

- hosts: main
  become: yes
  gather_facts: yes

  roles:

  ## Network
  - role: network/swag
    tags:
        - swag
        - network
        - docker
    when: enable_swag | default(False)

  ## Filesystem
  - role: filesystems/drives
    tags:
      - filesystems
      - drives
    when: enable_drives | default(False)

  - role: filesystems/mergerfs
    tags:
        - filesystems
        - mergerfs
    when: enable_mergerfs | default(False)

  - role: filesystems/mount
    tags:
        - filesystems
        - mount
    when: enable_mount | default(False)

  - role: homer
    tags:
        - homer
        - containers
    when: enable_homer | default(False)
  
  # # - role: ironicbadger.ansible_role_snapraid
  # #   become: yes
  # #   tags:
  # #     - filesystems
  # #     - snapraid
  # #   when: docker_persistent_data | default(False)
  tags:
    - main
- hosts: all
  become: yes
  gather_facts: yes

  roles:

  - role: quantumfate.zsh
    bocome: no
    vars:
      zsh_user: "{{ ansible_user }}"
    tags:
      - zsh
      - dotfiles
