---
- hosts: all
  become: yes
  gather_facts: no

  pre_tasks:
    - import_tasks: tasks/ssh_juggle_port.yml
      tags:
        - port

- hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
  - name: Requiring the list of services
    import_tasks: tasks/list_services.yml

  - name: Gathering information about proccessor architecture
    import_tasks: tasks/repo_arch.yml

  roles:
  - role: system/essential
    tags: 
      - system
    when: enable_essential | default(False)

  - role: geerlingguy.security
    tags:
      - security
    when: enable_security | default(False)

- hosts: all
  become: yes
  gather_facts: yes
  
  pre_tasks:
  - import_tasks: tasks/ssh_juggle_port.yml
    tags:
      - port
  - import_tasks: tasks/ensure_ssh_port.yml
  
  roles:

  - role: security/iptables
    tags:
      - security
      - iptables
    when: enable_iptables | default(False)

  - role: oefenweb.dns
    tags:
      - dns
    when: enable_dns | default(False)
  
  - role: system/docker
    tags: 
      - docker
    when: enable_docker | default(False)

- hosts: raspberrypi
  become: yes
  gather_facts: yes

  roles:

  ## Network
  - role: webservices/network/pihole
    tags: 
      - pihole
      - containers
    when: enable_pihole | default(False)

  - role: network/cloudflareddns
    tags: 
      - pihole
      - containers
    when: enable_cloudflareddns | default(False)

- hosts: quantumhome
  become: yes
  gather_facts: yes

  roles:

  ## Network
  - role: network/swag
    tags:
        - swag
    when: enable_swag | default(False)

  ## Filesystem
  - role: filesystems/mergerfs
    tags:
        - mergerfs
    when: enable_mergerfs | default(False)

  - role: filesystems/mount
    tags:
        - mount
    when: enable_mount | default(False)

  - role: homer
    tags:
        - homer
        - docker
    when: enable_homer | default(False)

  #   ### Run this at the end, when the environment is set
  #   - role: viasite-ansible.zsh
  #     tags:
  #       - zsh

  # # - role: ironicbadger.ansible_role_snapraid
  # #   become: yes
  # #   tags:
  # #     - snapraid
  # #   when: docker_persistent_data | default(False)

  # #
  # # homer
  # #
  # - role: homer
  #   become: no
  #   tags:
  #     - homer
  #     - containers
  #   when: enable_homer | default(False)
