---
- name: Collect only facts returned by ansible_architecture
  setup:
    gather_subset:
      - '!all'
      - '!<any valid subset>'
      - architecture

- name: Set amd64 arch
  ansible.builtin.set_fact:
    repo_arch: amd64
  when: ansible_architecture == "x86_64"

- name: Set arm64 arch
  ansible.builtin.set_fact:
    repo_arch: "{{ ansible_architecture }}"
  when: ansible_architecture == "arm64"