---
- name: SSH Port Juggle | Try connecting via SSH
  wait_for_connection:
    timeout: 5
  ignore_errors: true
  register: _ssh_port_result

- name: SSH Port Juggle | Set the ansible_port to the fallback default port
  set_fact:
    ansible_ssh_port: "{{ default_ssh_port }}"
  when:
    - _ssh_port_result is failed

- name: SSH Port Juggle | Try connecting again
  wait_for_connection:
    timeout: 5
  ignore_errors: true
  register: _ssh_port_default_result
  when:
    - _ssh_port_result is failed

- name: SSH Port Juggle | Fail
  fail: msg="Neither the configured ansible_port nor the fallback port 22 were reachable"
  when:
    - _ssh_port_result is failed
    - _ssh_port_default_result is defined
    - _ssh_port_default_result is failed