---
- name: Copy the unbound configuration file
  template:
    src: unbound.j2
    dest: "{{ docker_dir }}/{{ container_name }}/unbound.conf.d/pi-hole.conf"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644