---
- name: Add snapraid repository
  ansible.builtin.apt_repository:
    repo: 'ppa:tikhonov/snapraid'
    state: present
- name: Update the source for snapraid repo
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/tikhonov-ubuntu-snapraid-focal.list
    search_string: 'deb http://ppa.launchpad.net/tikhonov/snapraid/ubuntu focal main'
    line: '# deb http://ppa.launchpad.net/tikhonov/snapraid/ubuntu focal main'
    insertbefore: 'deb http://ppa.launchpad.net/tikhonov/snapraid/ubuntu cosmic main'

- name: install Snapraid
  ansible.builtin.apt:
    name: snapraid
    state: present
    update_cache: yes

- name: Write snapraid.conf to /etc/snapraid.conf
  template:
    src: snapraid.conf.j2
    dest: /etc/snapraid.conf
    mode: 0644