---
# Docker
docker_dir: /opt/docker/data 

## dns
dns_nameservers: ['1.1.1.1', '1.0.0.1']

# Pip packages
pip_install_packages: 
  - name: docker
  - name: awscli

# SSH (geerlingguy.security)
security_sudoers_passwordless: ['{{ ansible_user }}']
security_autoupdate_reboot: true
security_autoupdate_mail_to: '{{ email }}'
security_autoupdate_reboot_time: '23:00'
security_autoupdate_mail_on_error: false
security_fail2ban_enabled: false
security_ssh_restart_handler_state: restarted
security_sshd_state: started

# snapraid
snapraid_runner_email_address: "{{ email }}"
snapraid_data_disks: "{{ data_disks }}"
snapraid_parity_disks: "{{ parity_disks }}"
snapraid_content_files:
  - /var/snapraid.content

snapraid_config_excludes:
  - "*.unrecoverable"
  - /lost+found/
  - "*.!sync"
  - /tmp/
  - "/Downloads/*"

snapraid_runner_cron_jobs:
- { job: 'docker stop $(docker ps -q); rsync -avz --delete --exclude cache {{ docker_dir }} {{ mergerfs_root }}/docker_data; docker start $(docker ps -a -q) && {{ snapraid_runner_command }} ', name: 'snapraid_runner', weekday: '0', hour: '3' }

snapraid_scrub_schedule:
  minute: 0
  hour: 02
  weekday: 1

# ZSH
zsh_antigen_bundles_extras: [ nvm, git ]
