gitmail: leon-holm@outlook.de
gituser: Leon Holm
shell: /bin/zsh
packages:
  - neovim
  - htop
  - neofetch
  - lm-sensors
  - hddtemp
  - glances
  - zsh
  - git
  - curl
  - wget

########
# MISC #
########

# Functionality for drives, directories, redundancy etc
enable_nas_stuff: yes
#
# Mount
#

enable_mounting: yes

#
# MergerFS
#

enable_mergerfs: yes

mergerfs_root: /mnt/storage/

cache_root: /mnt/storage_cache/

#
# Snapraid
#

enable_snapraid: yes

snapraid_data_disks: "{{ disks }}"

snapraid_parity_disks: "{{ parity_disks }}"

snapraid_content_files:
  - /var/snapraid.content

snapraid_config_excludes:
  - "*.unrecoverable"
  - /lost+found/
  - "*.!sync"
  - /tmp/
  - "/Downloads/*"

snapraid_runner_cron_jobs:
- { job: 'docker stop $(docker ps -q); rsync -avz --delete --exclude cache {{ docker_dir }} {{ mergerfs_root }}/docker_data; docker start $(docker ps -a -q) && {{ snapraid_runner_command }} ', name: 'snapraid_runner', weekday: '0', hour: '3' }

#
# Docker
#

docker_dir: /opt/docker/data 

docker_deps:
  - 'apt-transport-https'
  - 'ca-certificates'
  - 'gnupg2'
  - 'software-properties-common'
  - 'python3-pip'
  - 'virtualenv'
  - 'python3-setuptools'
  - 'docker-compose'
  - 'lsb-release'

docker_packages:
  - 'docker-ce'
  - 'docker-ce-cli'
  - 'container.io'
  - 'docker-compose'
  - 'cgroupfs-mount'

#
# container
enable_nextcloud: yes
#
# Domains
#

subdomains: {
      'www': www,
      'home': 'home',
      'nextcloud': 'nextcloud',
}