gitmail: leon-holm@outlook.de
gituser: Leon Holm
shell: /bin/zsh
common_packages:
  - neovim
  - htop
  - neofetch
  - lm-sensors
  - glances
  - zsh
  - git
  - curl
  - wget
  - iptables

# Merges common packages with packages on specific hosts
total_packages: "{{ common_packages + specific_packages }}"

# MISC
my_project_source: /home/leonch/Documents/quantumhome
colorscheme: nord

# All enable variables
enable_nas_stuff: yes # Functionality for drives, directories, redundancy etc
## Filesystem
enable_mounting: yes
enable_mergerfs: yes
enable_snapraid: yes
## Webservices
enable_homer: yes
enable_media: no
enable_services: yes
enable_system: no
enable_homeautomation: no
### Services in detail
enable_bunkerized_nginx: no
enable_nextcloud: yes
enable_swag: yes
## Networking
enable_swag_internal: yes
enable_swag_public: yes
## Security
enable_security: yes # the whole group
enable_ikev2: no
enable_wireguard: no
enable_crowdsec: no

# MergerFS
mergerfs_root: /mnt/storage
cache_root: /mnt/storage_cache

# Snapraid
snapraid_runner_email_address: "{{ email }}"
snapraid_data_disks: "{{ data_disks }}"
snapraid_parity_disks: "{{ parity_disks }}"
snapraid_content_files:
  - /var/snapraid.content

snapraid_config_excludes:
  - "*.unrecoverable"
  - /lost+found/
  - "*.!sync"
  - /tmp/
  - "/Downloads/*"

snapraid_runner_cron_jobs:
- { job: 'docker stop $(docker ps -q); rsync -avz --delete --exclude cache {{ docker_dir }} {{ mergerfs_root }}/docker_data; docker start $(docker ps -a -q) && {{ snapraid_runner_command }} ', name: 'snapraid_runner', weekday: '0', hour: '3' }

snapraid_scrub_schedule:
  minute: 0
  hour: 02
  weekday: 1

# Docker
## Pip packages
pip_install_packages: 
  - name: docker
  - name: awscli

docker_dir: /opt/docker/data 

# ZSH
zsh_antigen_bundles_extras:
  - nvm

# Network
## vpn
vpn_network: "10.1.1.0/24"
## lan
IPv4_lan_network: "192.168.178.0/24"
IPv6_lan_network: "fd00::/8"
lan_gateway: "{{ '.'.join(IPv4_lan_network.split('.')[0:3]) }}.1"
dmz_network: "{{ '.'.join(lan_gateway.split('.')[0:2]) }}.44.0/24"
dmz_gateway: "{{ '.'.join(dmz_network.split('.')[0:3]) }}.1"
## swag
swag_network: "10.0.0.0/27"
swag_base: "{{ '.'.join(swag_network.split('.')[0:3]) }}"
swag_gateway: "{{ '.'.join(swag_network.split('.')[0:3]) }}.1"
swag_interface: vlan.4

# Domains
subdomains: {
      'www': www,
      'home': 'home',
      'nextcloud': 'nextcloud',
}

# Security
default_ssh_port: "22"