gitmail: leon-holm@outlook.de
gituser: Leon Holm
shell: /bin/zsh
packages:
  - neovim
  - htop
  - neofetch
  - lm-sensors
  - hddtemp
  - glances
  - zsh
  - git
  - curl
  - wget

########
# MISC #
########

my_project_source: /home/quantum/quantumhome

colorscheme: nord

# Functionality for drives, directories, redundancy etc
enable_nas_stuff: yes
#
# Mount
#

enable_mounting: yes

#
# MergerFS
#

enable_mergerfs: yes

mergerfs_root: /mnt/storage

cache_root: /mnt/storage_cache

#
# Snapraid
#

snapraid_runner_email_address: "{{ email }}"

enable_snapraid: yes

snapraid_data_disks: "{{ data_disks }}"

snapraid_parity_disks: "{{ parity_disks }}"

snapraid_content_files:
  - /var/snapraid.content

snapraid_config_excludes:
  - "*.unrecoverable"
  - /lost+found/
  - "*.!sync"
  - /tmp/
  - "/Downloads/*"

snapraid_runner_cron_jobs:
- { job: 'docker stop $(docker ps -q); rsync -avz --delete --exclude cache {{ docker_dir }} {{ mergerfs_root }}/docker_data; docker start $(docker ps -a -q) && {{ snapraid_runner_command }} ', name: 'snapraid_runner', weekday: '0', hour: '3' }

snapraid_scrub_schedule:
  minute: 0
  hour: 02
  weekday: 1

#
# Pip packages
#

pip_install_packages: 
  - name: docker
  - name: awscli
#
# Docker
#

docker_service_state: started

docker_service_enabled: true

docker_restart_handler_state: restarted

docker_install_compose: true

docker_compose_arch: x86_64

docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] {{ docker_repo_url }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_ignore_key_error: True
docker_apt_gpg_key: "{{ docker_repo_url }}/{{ ansible_distribution | lower }}/gpg"

docker_users:
 - "{{ ansible_user }}"

docker_dir: /opt/docker/data 

docker_deps:
  - 'apt-transport-https'
  - 'ca-certificates'
  - 'gnupg'
  - 'software-properties-common'
  - 'python3-pip'
  - 'virtualenv'
  - 'python3-setuptools'
  - 'docker-compose'
  - 'lsb-release'

docker_packages:
  - 'docker-ce'
  - 'docker-ce-cli'
  - 'container.io'
  - 'docker-compose'
  - 'cgroupfs-mount'

#
# container
#

#
# homer
enable_homer: yes

enable_media: false
enable_services: true
enable_systen: false
enable_homeautomation: false

#
# services

# nextcloud
enable_nextcloud: yes

#
# Network
#

# bunkerized-nginx
enable_bunkerized_nginx: no

# cloudflare
enable_cloudflare_ddns: yes

# vpn
vpn_network: "10.1.1.0/24"

# lan
lan_network: "192.168.178.0/24"

lan_address: "{{ '.'.join(lan_network.split('.')[0:3]) }}.230"

lan_gateway: "{{ '.'.join(lan_network.split('.')[0:3]) }}.1"

dmz_network: "{{ '.'.join(lan_gateway.split('.')[0:2]) }}.44.0/24"

dmz_gateway: "{{ '.'.join(dmz_network.split('.')[0:3]) }}.1"

# swag
enable_swag_internal: yes

enable_swag_public: yes

swag_network: "10.0.0.0/27"

swag_base: "{{ '.'.join(swag_network.split('.')[0:3]) }}"

swag_gateway: "{{ '.'.join(swag_network.split('.')[0:3]) }}.1"

swag_interface: vlan.4

#
# Domains
#

subdomains: {
      'www': www,
      'home': 'home',
      'nextcloud': 'nextcloud',
}

#
# Security
#
security_ssh_port: 22