gitmail: leonconnorholm@gmail.com
gituser: Leon Holm
email: leon-holm@outlook.de
shell: /bin/zsh

# MISC
my_project_source: /home/leonch/Documents/quantumhome
colorscheme: dracula
include_role_vars:
  - homer
  - unbound

# Includes all paths for webservices to be built
webservices_paths:
  - "roles/webservices/network"
  - "roles/webservices/services"

## time/local
ntp_timezone: '{{ timezone }}'
locale: en_US.UTF-8

# Security
default_ssh_port: "22"
security_ssh_allowed_users:
  - "{{ ansible_user }}"
