gitmail: leon-holm@outlook.de
gituser: Leon Holm
shell: /bin/zsh
packages:
  - neovim
  - htop
  - neofetch
  - lm-sensors
  - hddtemp
  - glances
  - zsh
  - git
  - curl
  - wget

#
# MergerFS
#

enable_mergerfs: yes

mergerfs_root: /mnt/storage

cache_root: /mnt/storage_cache