---
- name: Ensuring that git is configured for basic usage
  template:
    src: git-config.j2
    dest: "/home/{{ ansible_user }}/.gitconfig"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644