---
- name: Set the name of a sudo group
  set_fact:
    sudo_group: sudo

- name: Enable passwordless sudo for "{{ ansible_user }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Copy the public SSH key 
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ ansible_ssh_public_key_file }}"
    path: "/home/{{ ansible_user }}/.ssh/authorized_keys"

- name: Set the default shell
  user: 
    name: "{{ ansible_user }}"
    shell: "{{ shell }}"
