---
- name: Make sure the cloudflareddns container is created and running
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "oznu/cloudflare-ddns:latest"
    pull: yes
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "API_KEY": "{{ cloudflare_dns_token }}"
      "ZONE": "{{ host }}"
      "PROXIED": "true"
      "SUBDOMAIN": "ddns"
    restart_policy: unless-stopped
  register: wait_result
  
- name: Debug pihole container
  debug:
    msg: "{{ 'Failed with message: ' ~ wait_result.msg if wait_result.failed else 'Success enabling and running the container ' ~ container_name }}"