---
- name: Ensure group docker exists
  group:
    name: docker
    state: present

- name: Add user user to group docker
  user:
    name: "{{ ansible_user }}"
    groups:
      - docker
    append: yes
  register: "{{ wait_result }}"

- name: Debug ansible_user 
  debug:
    msg: "{{ 'Failed with message: ' ~ wait_result.msg if wait_result.failed else 'Success adding ' ~ ansible_user ~ ' to group docker' }}" 

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Make sure Docker is running and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: Stop and remove all the disabled containers if they are explicitly set to no
  become: false
  docker_container:
    name: "{{ main_key.path.split('/')[-1] }}"
    state: absent
  # You really want to make sure here the variable is actually defined...
  # If you check for the variable without lookup() you might delete container
  # that you didn't want to remove
  when: not 'enable_' ~ main_key.value.role_name is undefined and not 'enable_' ~ main_key.value.role_name
  with_dict: 
    - "{{ web_services_to_build }}"
  loop_control:
    loop_var: main_key
   
- name: Check if required variables are set
  when: docker_backup_data
  block:
    - name: Check if src directory is valid
      fail: 
        msg: "Host has backup data but no valid source has been specified"
      when: docker_backup_src == ''
    - name: Check if there is persistent data that can be backed up
      fail: 
        msg: "Host is supposed to have backup data but host is not supposed to have persistant storage"
      when: not docker_persistent_data

- name: Raise alert when persistent data exists but backup is disabled
  when: not docker_backup_data
  block:
    - name: Check if src directory is set
      fail: 
        msg: "Host has no backup data but a valid backup src has been specified"
      when: docker_backup_src != ''
      failed_when: false
      changed_when: false

    - name: Check if there is persistent data that can be backed up
      fail: 
        msg: "Host has no backup data but host has data that might be backed up"
      when: docker_persistent_data
      failed_when: false
      changed_when: false

- name: Handle persistent data
  become: false
  when: docker_persistent_data
  block:
  - name: Set the mandatory docker_dir variable
    set_fact:
      docker_dir: "{{ docker_dir }}" # required. The C(set_fact) module takes key=value pairs as variables to set in the playbook scope. Or alternatively, accepts complex arguments using the C(args:) statement.
  - name: Check if the persistent data folder exists on the remote machine
    stat:
      path: "{{ docker_dir }}"
    register: persistent_data

  - name: Check if the persistent data folder is empty
    find:
      paths:
        - "{{ docker_dir }}/"
      recurse: yes
    register: persistent_data_find

  - name: Create the persistent data folder on the remote machine
    become: true
    file:
      dest: "{{ docker_dir }}"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0755
      recurse: yes
    when: not persistent_data.stat.exists

  - name: Restoring data
    when: docker_backup_data
    block:
    - name: Restore the docker directory folder from the MergerFS array
      synchronize:
        src: "{{ docker_backup_src }}"
        dest: "{{ docker_dir }}/"
        delete: true
        recursive: yes
      delegate_to: "{{ inventory_hostname }}"
      when: (persistent_data_find.matched < 20 or not persistent_data.stat.exists)
      failed_when: false
      changed_when: false

  - name: Chmod the data folder
    become: true
    file:
      dest: "{{ docker_dir }}"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      recurse: yes