---
- name: Install the macvlan service file
  template:
    src: 'macvlan.service.j2'
    dest: '/etc/systemd/system/macvlan.service'
    owner: root
    group: root
    mode: 0644
  notify: 
    - Restart macvlan service
  register: macvlan_service_install