---

- name: Importing essential tasks
  include_tasks: essential.yml

- name: Importing user settings
  include_tasks: user.yml

- name: Importing remove snap
  include_tasks: remove_snap.yml

- name: Importing netplan
  include_tasks: netplan.yml
  when: enable_network_interface | default(False)

- name: Importing macvlan
  include_tasks: macvlan.yml
  when: enable_macvlan_interface | default(False)
  
- name: Importing powersaving
  include_tasks: powersaving.yml
  when: enable_powersaving | default(False)
