---
- name: Set the name of a sudo group
  ansible.builtin.set_fact:
    sudo_group: sudo

- name: Enable passwordless sudo for ansible user
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
  register: wait_result
  
- name: Debug ansible_user 
  debug:
    msg: "{{ 'Failed with message: ' ~ wait_result.msg if wait_result.failed else 'Success enabling passwordless sudo for ' ~ ansible_user }}" 

- name: Copy the public SSH key 
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ ansible_ssh_public_key_file }}"
    path: "/home/{{ ansible_user }}/.ssh/authorized_keys"

- name: Ensuring that git is configured for basic usage
  template:
    src: git-config.j2
    dest: "/home/{{ ansible_user }}/.gitconfig"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Create the script folder
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.script
    state: directory
    mode: '755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"