---
- name: Create a homer network
  community.docker.docker_network:
    name: homer_network
    state: present

- name: Make sure the Homer container is created and running
  community.docker.docker_container:
    name: 'homer'
    image: "b4bz/homer"
    networks:
      - name: homer_network
      - name: swag_internal_macvlan
        ipv4_address: "{{ swag_address }}"
    pull: true
    state: 'started'
    env:
      "UID": "{{ guid }}"
      "GID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/www/assets"
    restart_policy: unless-stopped