---
- name: Install pip
  package:
    name: python3-pip
    state: present

- name: Install the Xresources parser
  pip:
    name: xparser

- name: Install the Xresources file
  copy:
    dest: "/home/{{ ansible_user }}/.Xresources"
    src: "files/colorschemes/{{ colorscheme | lower }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Register a variable from json colors
  ansible.builtin.set_fact:
    colors: "{{ lookup('file', 'dracula.json') | from_json }}"

- name: debug x
  debug:
    var: colors
