---
ansible_host: 192.168.1.23
ansible_user: sao
ansible_connection: ssh
ansible_ssh_port: "{{ security_ssh_port }}"
ansible_ssh_private_key_file: /home/leonch/.ssh/quantumhome
ansible_ssh_public_key_file: "{{ lookup('file', '~/.ssh/quantumhome.pub') }}"
ansible_become_password: "{{ quantumhome_sudo_password }}"