---
#
# Connection
#
ansible_host: 192.168.178.96
ansible_user: sao
ansible_connection: ssh
ansible_ssh_private_key_file: /home/quantum/.ssh/quantumhome
ansible_ssh_public_key_file: "{{ lookup('file', '~/.ssh/quantumhome.pub') }}"

#
# System specific variables
#
timezone: Europe/Amsterdam
guid: "1000"

#
# Drives
#

# lvm 
main_volume_group: ubuntu-vg
vg_cache_drive: Cache1

# src
src_parity1: /dev/sda/parity/Parity1

src_data1: /dev/sdb/data/Data1
src_data2: /dev/sdc/data/Data2
src_data3: /dev/sdd/data/Data3

src_cache1: "/dev/cache/{{ main_volume_group }}/{{ vg_cache_drive }}"
src_cache2: /dev/sde/cache/Cache2

# Mount Points
mnt_parity1: /mnt/parity1

mnt_data1: /mnt/data1
mnt_data2: /mnt/data2
mnt_data3: /mnt/data3

mnt_cache1: /mnt/cache1
mnt_cache2: /mnt/cache2

# actual disks
parity_disks: 
  - { path: "{{ mnt_parity1 }}", src: "{{ src_parity1 }}" , content: true }

data_disks:
  - { path: "{{ mnt_data1 }}", src: "{{ src_data1 }}", content: true }
  - { path: "{{ mnt_data1 }}", src: "{{ src_data1 }}", content: true }
  - { path: "{{ mnt_data1 }}", src: "{{ src_data1 }}", content: true }

cache_disks:
  - { path: "{{ mnt_cache1 }}", src: "{{ src_cache1 }}", content: true }
  - { path: "{{ mnt_cache2 }}", src: "{{ src_cache2 }}", content: true }

# Networks
#
lan_network: "192.168.178.96/24"

swag_network: "10.0.0.0/27"

swag_base: "{{ '.'.join(swag_network.split('.')[0:3]) }}"
