---
#
# Connection
#
host_become_password: "{{ quantumhome_sudo_password }}"

ssh_keys:
  - name: default user ssh key
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', '~/.ssh/quantumhome.pub') | default('') }}"


# Apt mirrors
version: jammy
apt_mirror: https://mirror.dogado.de/ubuntu/


# System specific variables
timezone: Europe/Amsterdam
guid: "1000"

