---
ansible_host: 192.168.178.96
ansible_user: sao
ansible_connection: ssh
ansible_ssh_private_key_file: /home/quantum/.ssh/quantumhome
ansible_ssh_public_key_file: "{{ lookup('file', '~/.ssh/quantumhome.pub') }}"