---
- name: Create the volume group for one of the cache drives and assign the label cache
  community.general.lvol:
    vg: "{{ main_volume_group }}"
    lv: "{{ vg_cache_drive }}"
    size: 100%FREE
  failed_when: false
  changed_when: false

- name: Create the mergerfs storage folder "{{ mergerfs_root }}"
  ansible.builtin.file:
    path: "{{ mergerfs_root }}"
    state: directory
    mode: '755'
    owner: "root"
    group: "root"

- name: Create the mergerfs storage folder "{{ mergerfs_root }}_slow"
  ansible.builtin.file:
    path: "{{ mergerfs_root }}_slow"
    state: directory
    mode: '755'
    owner: "root"
    group: "root"

- name: Create the mergerfs storage folder "{{ cache_root }}"
  ansible.builtin.file:
    path: "{{ cache_root }}"
    state: directory
    mode: '755'
    owner: "root"
    group: "root"

- name: Rename the cache drive label
  ansible.builtin.script:
    cmd: "{{ playbook_dir }}/roles/filesystems/mount/templates/rename-lvmdrive.j2"
    creates: "/home/{{ ansible_user }}/.script/rename-lvmdrive"

- name: Mount the Parity drives used for Snapraid
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: xfs
    state: mounted
    passno: "2"
  with_items: "{{ parity_disks }}"
  when: parity_disks[0] is defined

- name: Mount the data drives
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: xfs
    state: mounted
    passno: "2"
  with_items: "{{ data_disks }}"
  when: data_disks[0] is defined

- name: Mount the Cache drives
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: ext4
    state: mounted
    passno: "2"
  with_items: "{{ cache_disks }}"
  when: cache_disks[0] is defined

- name: Mount the MergerFS cached Array
  ansible.posix.mount:
    path: "{{ mergerfs_root }}"
    src: /mnt/cache*:/mnt/data*
    opts: category.create=lfs,direct_io,defaults,allow_other,moveonenospc=1,minfreespace=50G,fsname=mergerfs,uid=1000,gid=1000
    fstype: fuse.mergerfs
    state: mounted
  when: data_disks[0] is defined

- name: Mount the MergerFS data Array
  ansible.posix.mount:
    path: "{{ mergerfs_root }}_slow"
    src: /mnt/data*
    opts: direct_io,defaults,allow_other,moveonenospc=1,minfreespace=500G,fsname=mergerfs_slow,uid=1000,gid=1000
    fstype: fuse.mergerfs
    state: mounted
  when: data_disks[0] is defined

- name: Mount the MergerFS cache Array
  ansible.posix.mount:
    path: "{{ cache_root }}"
    src: /mnt/cache*
    opts: direct_io,defaults,allow_other,fsname=mergerfs_cache,category.create=mfs
    fstype: fuse.mergerfs
    state: mounted
  when: cache_disks[0] is defined