- name: Get infos on SWAG container
  community.docker.docker_container_info:
    name: swag_internal
  register: result

- name: Update the SWAG DNS record to Cloudflare
  community.general.cloudflare_dns:
    zone: "{{ host }}"
    record: "{{ host_local }}"
    type: A
    value: "{{ result.container.NetworkSettings.Networks.swag_internal_macvlan.IPAddress }}"
    account_email: "{{ cf_email }}"
    account_api_key: "{{ cloudflare_dns_token }}"
    ttl: 3600
    priority: 10
    proxied: false
  failed_when: false
  changed_when: false

