---
- name: Create an internal macvlan network
  when: enable_swag_internal | default(False)
  community.docker.docker_network:
      name: swag_internal_macvlan
      driver: macvlan
      driver_options:
          parent: '{{ swag_interface }}'
      ipam_config:
          - subnet: '{{ swag_network }}'
            gateway: '{{ swag_gateway }}'
  notify:
      - Restart swag internal

- name: Create a public macvlan network
  when: enable_swag_public | default(False)
  community.docker.docker_network:
      name: swag_public_macvlan
      driver: macvlan
      driver_options:
          parent: '{{ dmz_interface }}'
      ipam_config:
          - subnet: '{{ dmz_network }}'
            gateway: '{{ dmz_gateway }}'
  notify:
      - Restart swag public