---
- name: Make sure the pihole container is created and running
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "pihole/pihole:latest"
    privileged: yes
    hostname: "{{ container_name }}"
    pull: yes
    state: 'started'
    env:
      "TZ": "{{ timezone }}"
      "WEBPASSWORD": "{{ pihole_password }}"
      "PIHOLE_DNS_": "{{ pi_dns }}"
      "FTLCONF_REPLY_ADDR4": "{{ ip_address }}"
      "WEBTHEME": "default-dark"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/volume:/etc/pihole:rw"
      - "{{ docker_dir }}/{{ container_name }}/config/hosts:/etc/hosts:ro"
      - "{{ docker_dir }}/{{ container_name }}/config/resolv.conf:/etc/resolv.conf:ro"
      - "{{ docker_dir }}/{{ container_name }}/config/dnsmasq.conf:/etc/dnsmasq.d/02-network.conf:ro"
      - "{{ docker_dir }}/{{ container_name }}/config/pihole-FTL.conf:/etc/pihole/pihole-FTL.conf:ro"
    ports:
      - "80/tcp"
      - "443/tcp"
      - "67/udp"
      - "53/tcp"
      - "53/udp"
    networks:
      - name: "{{ pi_network }}"
        ipv4_address: "{{ ip_address }}"
    restart_policy: unless-stopped
  register: wait_result

- name: Debug pihole container
  debug:
    msg: "{{ 'Failed with message: ' ~ wait_result.msg if wait_result.failed else 'Success enabling and running the container ' ~ container_name }}" 
