---
- name: Add webservice mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.value.ip_address }} {{ item.value.url }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.value.url }}"
  when: item.value.ip_address is defined and item.value.url is defined and item.value.ip_address != '' and item.value.url != ''
  loop: "{{ web_services_to_build | dict2items }}"

- name: Add roles mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.value.ip_address }} {{ item.value.url }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.value.url }}"
  when: item.value.ip_address is defined and item.value.url is defined and item.value.ip_address != '' and item.value.url != ''
  loop: "{{ roleswithvariables_to_build | dict2items }}"

# - name: Copy the template file for custom domain names for local network
#   template:
#     src: custom.list.j2
#     dest:  "{{ docker_dir }}/{{ container_name }}/pihole/custom.list"
#     owner: "{{ ansible_user }}"
#     group: "{{ ansible_user }}"
#     mode: 0644