---
- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip_address }} {{ item.url }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.url }}"
  loop:
    - "{{ web_services_to_build }}"
