---
- name: "Simple Roles: Including roles ..."
  include_role:
    name: "{{ outer_item.value.path }}"
    apply:
      tags:
        - outer_item.value.tag_primary
        - outer_item.value.tag_secondary
        - simple
  when: "('enable_simple_' + outer_item.value.role_name | default(False))"
  with_dict: "{{ simple_roles_to_build }}"
  loop_control:
    loop_var: outer_item